version: '3'
services:
  db:
    image: postgres:13
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance_calc
    volumes:
      # TODO: stick these in subfolders / `*` import them?
      - ./database/000-users.sql:/docker-entrypoint-initdb.d/000-users.sql
      - ./database/001-extensions.sql:/docker-entrypoint-initdb.d/001-extensions.sql
      - ./database/002-schema.sql:/docker-entrypoint-initdb.d/002-schema.sql
      - ./database/003-user-table.sql:/docker-entrypoint-initdb.d/003-user-table.sql
      - ./database/004-scenario-table.sql:/docker-entrypoint-initdb.d/004-scenario-table.sql
      - ./database/005-debt-table.sql:/docker-entrypoint-initdb.d/005-debt-table.sql
      - ./database/006-debt-payment-table.sql:/docker-entrypoint-initdb.d/006-debt-payment-table.sql
      - ./database/007-debt-projection-table.sql:/docker-entrypoint-initdb.d/007-debt-projection-table.sql
      - ./database/008-savings-account-table.sql:/docker-entrypoint-initdb.d/008-savings-account-table.sql
      - ./database/009-savings-payment-table.sql:/docker-entrypoint-initdb.d/009-savings-payment-table.sql
      - ./database/010-savings-projection-table.sql:/docker-entrypoint-initdb.d/010-savings-projection-table.sql
      - ./database/seed/000-users-seed-data.sql:/docker-entrypoint-initdb.d/999-users-seed-data.sql

  api:
    image: calgarymichael/finance-calc-backend
    build:
      context: finance-calc/
      dockerfile: build/Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_USER: finance_calc
      DB_PASSWORD: finance_calc
      DB_NAME: finance_calc
      DB_HOST: db
      DB_PORT: 5432
      JWT_KEY: dev
    depends_on:
      - db

  webapp:
    image: calgarymichael/finance-calc-frontend
    build:
      context: webapp/
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    depends_on:
      - api
