version: 2.1
jobs:
  test-backend:
    docker:
      # specify the version
      - image: circleci/golang:1.14

    working_directory: /go/src/github.com/calgarymichael/finance-calc/finance-calc
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: pwd
      - run: go get -v -t -d ./...
      - run: go test -v ./...


workflows:
  test-and-build:
    jobs:
      - test-backend

