version: 2.1
jobs:
  test-backend:
    docker:
      - image: circleci/golang:1.14

    working_directory: /go/src/github.com/calgarymichael/finance-calc
    steps:
      - checkout

      - run:
          name: download package(s)
          command: |
            cd finance-calc
            go get -v -t -d ./...

      - run:
          name: run tests
          command: |
            cd finance-calc
            go test -v ./...


workflows:
  test-and-build:
    jobs:
      - test-backend

