export const UPDATE_SORT_KEY = "UPDATE_SORT_KEY"
export const UPDATE_SORT_DIRECTION = "UPDATE_SORT_DIRECTION"
export const UPDATE_SCENARIO = "UPDATE_SCENARIO";
export const SAVE_PROJECTIONS = "SAVE_PROJECTIONS";

